spring.datasource.url=jdbc:postgresql://ep-cool-wind-apqfs6tm-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

groq.api.key=${GROQ_KEY}
telegram.bot.token=${TELEGRAM_TOKEN}

server.port=${PORT:8080}