# Conexi\u00F3n a la base de datos Neon en la nube
spring.datasource.url=jdbc:postgresql://neondb_owner:npg_U8QzmFv6MYBe@ep-cool-wind-apqfs6tm-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_U8QzmFv6MYBe

# Para que las tablas se creen autom\u00E1ticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Marcadores para tus llaves secretas (Render las llenar\u00E1 autom\u00E1ticamente)
groq.api.key=${GROQ_KEY}
telegram.bot.token=${TELEGRAM_TOKEN}

# Puerto del servidor para que Render funcione
server.port=${PORT:8080}